apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finlyzerapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: finlyzer.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: finlyzerapp
                port:
                  number: 80
